// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWolq_dKDcVVeP_DImQlMXBJn_v7LRu2k',
    appId: '1:269479924554:web:682512ebecb01a867467b3',
    messagingSenderId: '269479924554',
    projectId: 'gso43-irgy',
    authDomain: 'gso43-irgy.firebaseapp.com',
    storageBucket: 'gso43-irgy.firebasestorage.app',
    measurementId: 'G-PYKYC5F2SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf1U_E0DbQPp0CQZWaSGMsPAj_P3gi74k',
    appId: '1:269479924554:android:8cf4f441453b24e77467b3',
    messagingSenderId: '269479924554',
    projectId: 'gso43-irgy',
    storageBucket: 'gso43-irgy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qZzGoOfdsJXQWs_znwMCZSQxBX8rXAQ',
    appId: '1:269479924554:ios:bb805560d98983de7467b3',
    messagingSenderId: '269479924554',
    projectId: 'gso43-irgy',
    storageBucket: 'gso43-irgy.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIrgy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3qZzGoOfdsJXQWs_znwMCZSQxBX8rXAQ',
    appId: '1:269479924554:ios:bb805560d98983de7467b3',
    messagingSenderId: '269479924554',
    projectId: 'gso43-irgy',
    storageBucket: 'gso43-irgy.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIrgy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWolq_dKDcVVeP_DImQlMXBJn_v7LRu2k',
    appId: '1:269479924554:web:10250155c6a3b9df7467b3',
    messagingSenderId: '269479924554',
    projectId: 'gso43-irgy',
    authDomain: 'gso43-irgy.firebaseapp.com',
    storageBucket: 'gso43-irgy.firebasestorage.app',
    measurementId: 'G-LD16MQ00D5',
  );
}
